# Generated by Django 5.1.3 on 2024-12-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('workshop', '0010_delete_workshopservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshop.workshop'),
        ),
    ]
