# Generated by Django 5.1.3 on 2024-12-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_is_approved_service_workshop'),
        ('workshop', '0010_delete_workshopservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='workshop',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshop.workshop'),
        ),
    ]
