# Generated by Django 5.1.3 on 2024-12-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='service',
            name='workshop',
        ),
    ]
