# Generated by Django 5.1.3 on 2024-12-20 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='document',
            field=models.FileField(default='https://fixngo-images.s3.eu-north-1.amazonaws.com/media/profile_images/58/harman4.jpg', upload_to='workshop_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='workshop',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
