# Generated by Django 5.1.3 on 2024-12-20 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workshop_approval_status_workshop_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='document',
            field=models.FileField(upload_to='workshop_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
