# Generated by Django 5.1.3 on 2024-12-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_workshopservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopservice',
            name='category',
        ),
        migrations.AlterField(
            model_name='workshopservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopservice',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshop.workshop'),
        ),
    ]
