# Generated by Django 5.1.3 on 2024-12-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_workshopservice_admin_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkshopService',
        ),
    ]
