# Generated by Django 5.1.3 on 2025-01-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_workshop_latitude_workshop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
