# Generated by Django 5.1.3 on 2025-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_alter_workshop_latitude_alter_workshop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
