# Generated by Django 5.1.3 on 2025-01-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_status'),
        ('workshop', '0014_alter_workshop_latitude_alter_workshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopservice',
            name='admin_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_workshop_services', to='service.service'),
        ),
    ]
