# Generated by Django 5.1.3 on 2025-01-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_workshopservice_admin_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopservice',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
