# Generated by Django 5.1.3 on 2025-01-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_workshopservice_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='longitude',
        ),
    ]
