# Generated by Django 5.1.3 on 2025-01-16 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_remove_workshop_latitude_remove_workshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
