# Generated by Django 5.1.3 on 2025-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_workshop_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
