# Generated by Django 5.1.3 on 2025-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_alter_workshop_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
