# Generated by Django 5.1.3 on 2025-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0022_workshop_latitude_workshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='profile_image',
            field=models.URLField(default='https://fixngo-new-images.s3.us-east-1.amazonaws.com/media/profile_images/10/AutoRepairShopOceanside.jpg', max_length=500),
        ),
    ]
