# Generated by Django 5.1.3 on 2025-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0023_workshop_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='profile_image',
            field=models.URLField(max_length=500),
        ),
    ]
