# Generated by Django 5.1.3 on 2025-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0024_alter_workshop_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workshopotp',
            name='email',
            field=models.EmailField(default='workk@gmail.com', max_length=254),
        ),
    ]
