# Generated by Django 5.1.3 on 2024-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_profile_image_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(max_length=500),
        ),
    ]
