# Generated by Django 5.1.3 on 2024-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='amal@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(default='5454', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default='abhi', max_length=150, unique=True),
        ),
    ]
