# Generated by Django 5.1.3 on 2024-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_otp_user_otp_email_otp_phone_otp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
