# Generated by Django 5.1.3 on 2024-12-29 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_otp_email_alter_otp_phone_alter_otp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='username',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
