# Generated by Django 5.1.3 on 2025-01-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
