# Generated by Django 5.1.3 on 2025-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='workshop_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
